[project]
name = "leetcode-py-cheatsheet"
version = "0.1.0"
description = "Quick reference for common LeetCode Python techniques and patterns."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.7.4",
]
