name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache uv installation
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/uv
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-uv-${{ hashFiles('.github/workflows/test.yml') }}

    - name: Install uv
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Run Tests
      run: |
        uv run --python 3.13 python -m unittest discover test -v

